---
# tasks file for backup
- name: Taking instance snapshot
  import_tasks: instance_snapshot.yml
  when: options.instance_snapshot

- name: Taking volume snapshot
  import_tasks: volume_snapshot.yml
  when: options.volume_snapshot